stages:
  stage_1:
    cmd: python stage_1.py
    deps:
      - stage_1.py
    outs:
       - artifact.txt

  stage_2:
    cmd: python stage_2.py
    deps:
      - artifact.txt
      - stage_2.py
      